name: Compilar APK Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Obter codigo do repositorio
        uses: actions/checkout@v4

      - name: Compilar APK com Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: master

      - name: Disponibilizar APK para descarregar
        uses: actions/upload-artifact@v4
        with:
          name: Manutencao_Pro_APK
          path: bin/*.apk
